version: '3.4'

services:
  macaetechwebapp:
    image: luizcarlosfaria/appmacaetech
    environment:
      - MinhaApp__Connectionstring=TesteCompose      
    build:
      context: .
      dockerfile: MacaeTechWebApp/Dockerfile
    deploy:
      replicas: 6     
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
