version: '3.4'

services:
  macaetechwebapp:
    image: luizcarlosfaria/appmacaetech
    environment:
      - MinhaApp__Connectionstring=TesteCompose      
    build:
      context: .
      dockerfile: MacaeTechWebApp/Dockerfile   